language: python
python:
   - "2.6"
   - "2.7"

install:
   - pip install -e git+https://github.com/CybOXProject/python-cybox.git#egg=python-cybox
   - pip install . --use-mirrors

script:
   - nosetests
